[any.drivers.motrona_terminal_voltage]
type="motrona_ax350"
title="Motrona terminal voltage"
url="http://127.0.0.1:22100/api/latest"

[any.drivers.g64]
type="mirion_g64"
title="Mirion G64 Radiation"
url="http://127.0.0.1:22102/api/latest"

[any.drivers.keithley]
type="keithley"
title="keithley"
url="http://127.0.0.1:22101/api/latest"

#[any.drivers.motrona_terminal_voltage]
#type="motrona_ax350"
#title="Motrona Terminal Voltage"
#url="http://127.0.0.1:22103/api/latest"



